// Points the Xcode scheme at storekit/Monstir.storekit so local StoreKit testing
// survives `expo prebuild`.
//
// Why a plugin: the StoreKit configuration is a *scheme run option*, and ios/ is
// gitignored and fully regenerated by prebuild — so setting it by hand in Xcode
// (Product → Scheme → Edit Scheme → Run → Options) works until the next prebuild
// and then silently disappears, at which point purchases stop resolving and it
// looks like an expo-iap bug.
//
// The file itself lives at repo root (storekit/) rather than under ios/ so it is
// version-controlled; the plugin copies it into the generated project and adds the
// StoreKitConfigurationFileReference the scheme needs.
//
// NB: this only affects launches made *by Xcode*. Xcode is what injects the
// configuration into the process, so `xcrun simctl launch` and `expo run:ios`
// bypass it — run from Xcode (Cmd+R) when you want the fake products.

const { withXcodeProject, withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SOURCE_REL = 'storekit/Monstir.storekit';
const DEST_NAME = 'Monstir.storekit';

/** Copy the .storekit file into ios/ so the scheme reference resolves. */
const withStoreKitFile = (config) =>
  withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const src = path.join(cfg.modRequest.projectRoot, SOURCE_REL);
      if (!fs.existsSync(src)) {
        console.warn(`[withStoreKitConfig] ${SOURCE_REL} not found — skipping.`);
        return cfg;
      }
      fs.copyFileSync(src, path.join(cfg.modRequest.platformProjectRoot, DEST_NAME));
      return cfg;
    },
  ]);

/** Add <StoreKitConfigurationFileReference> to the scheme's LaunchAction. */
const withSchemeReference = (config) =>
  withXcodeProject(config, (cfg) => {
    const projectName = cfg.modRequest.projectName;
    const scheme = path.join(
      cfg.modRequest.platformProjectRoot,
      `${projectName}.xcodeproj`,
      'xcshareddata',
      'xcschemes',
      `${projectName}.xcscheme`
    );
    if (!fs.existsSync(scheme)) {
      console.warn('[withStoreKitConfig] scheme not found — skipping.');
      return cfg;
    }

    let xml = fs.readFileSync(scheme, 'utf8');
    if (xml.includes('StoreKitConfigurationFileReference')) return cfg;

    // Nest the reference inside LaunchAction, which is where Xcode reads it from.
    // The path is relative to the .xcodeproj's parent (ios/), hence the leading
    // "../" that Xcode itself writes.
    const reference =
      `\n      <StoreKitConfigurationFileReference\n` +
      `         identifier = "../${DEST_NAME}">\n` +
      `      </StoreKitConfigurationFileReference>`;

    xml = xml.replace(/(<LaunchAction[\s\S]*?>)/, `$1${reference}`);
    fs.writeFileSync(scheme, xml);
    return cfg;
  });

module.exports = (config) => withSchemeReference(withStoreKitFile(config));
